### ISSUE TITLE
Remove Special-Case Student Affairs and ATLStuAffairs Redirects+Rewrites

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/cs-web-config#4]
- The ATLStuAffairs redirects will no longer function since the hostname was moved to Bazooka
- The Student Affairs redirects are no longer necessary since Google and other search engine indices have been updated by now
- The Student Affairs rewrites are no longer necessary since the subsite is now mu-studentaffairs rather than studentaffairs

**Comment by Sporkyy** [comment]
Removed the following:
- Redirect /www/studentaffairs/recreationsports (HTTP)
- Redirect /www/studentaffairs/recreationsports (HTTPS)
- Redirect studentaffairs.mercer.edu/recreationsports (HTTP)
- Redirect studentaffairs.mercer.edu/recreationsports (HTTPS)
- Redirect /www/mu-atlstuaffairs/wellness (HTTP)
- Redirect /www/mu-atlstuaffairs/wellness (HTTPS)
- Redirect atlstuaffairs.mercer.edu/wellness (HTTP)
- Redirect atlstuaffairs.mercer.edu/wellness (HTTPS)
- Redirect /www/studentaffairs/careerservices (HTTP)
- Redirect /www/studentaffairs/careerservices (HTTPS)
- Redirect studentaffairs.mercer.edu/careerservices (HTTP)
- Redirect studentaffairs.mercer.edu/careerservices (HTTPS)
- Redirect /www/studentaffairs/counseling (HTTP)
- Redirect /www/studentaffairs/counseling (HTTPS)
- Redirect studentaffairs.mercer.edu/counseling (HTTP)
- Redirect studentaffairs.mercer.edu/counseling (HTTPS)
- Redirect /www/mu-atlstuaffairs/housing (HTTP)
- Redirect /www/mu-atlstuaffairs/housing (HTTPS)
- Redirect atlstuaffairs.mercer.edu/housing (HTTP)
- Redirect atlstuaffairs.mercer.edu/housing (HTTPS)
- Redirect /www/studentaffairs/housing (HTTP)
- Redirect /www/studentaffairs/housing (HTTPS)
- Redirect studentaffairs.mercer.edu/housing (HTTP)
- Redirect studentaffairs.mercer.edu/housing (HTTPS)
- Redirect /www/studentaffairs/disabilityservices (HTTP)
- Redirect /www/studentaffairs/disabilityservices (HTTPS)
- Redirect studentaffairs.mercer.edu/disabilityservices (HTTP)
- Redirect studentaffairs.mercer.edu/disabilityservices (HTTPS)
- Redirect /www/studentaffairs/campuslife (HTTP)
- Redirect /www/studentaffairs/campuslife (HTTPS)
- Redirect studentaffairs.mercer.edu/campuslife (HTTP)
- Redirect studentaffairs.mercer.edu/campuslife (HTTPS)
- Redirect /www/mu-atlstuaffairs/campus-life (HTTP)
- Redirect /www/mu-atlstuaffairs/campus-life (HTTPS)
- Redirect atlstuaffairs.mercer.edu/campus-life (HTTP)
- Redirect atlstuaffairs.mercer.edu/campus-life (HTTPS)
- Rewrite Files studentaffairs.mercer.edu to studentaffairs
- Rewrite Directories studentaffairs.mercer.edu to studentaffairs
